# Streamlit secrets.toml template
# Rename this file to secrets.toml and put your keys here.

[api]
# Example: DeepSeek API key
DEEPSEEK_API_KEY = "your-api-key-here"

[settings]
# Default language (e.g., 'English', 'Hindi')
DEFAULT_LANGUAGE = "English"

# Default temperature (controls randomness: 0 = strict, 1 = creative)
DEFAULT_TEMPERATURE = 0.7
